---
name: Gammu
version: dev
slug: gammu
description: Gammu add-on by Cayetano
url: https://github.com/Foguet/addon-gammu
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  seconds_between_quotes: 5
  device: /dev/ttyUSB0
  pin: 6651
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
startup: before
ports:
  5000/tcp: 5000
